workspace = {}

[package]
name = "verso"
version = "0.0.1"
authors = ["Wu Yu Wei"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "An innovative web browser"
readme = "README.md"
homepage = "https://versotile.org/verso"
repository = "https://github.com/versotile-org/verso"
documentation = "https://docs.versotile.org/verso"
categories = ["web-programming"]

[package.metadata.packager]
name = "verso"
product-name = "verso"
identifier = "org.versotile.verso"
version = "0.0.1"
before-each-package-command = "cargo build --release --features packager"
out-dir = "target/release"
resources = [
  "resources",
  "icons",
  "target/release/build/**/libEGL.dll",
  "target/release/build/**/libGLESv2.dll",
]
icons = ["icons/icon256x256.png", "icons/icon.ico"]

[package.metadata.packager.nsis]
appdata-paths = ["$LOCALAPPDATA/$IDENTIFIER"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

[features]
default = []
packager = ["dep:cargo-packager-resource-resolver"]

[build-dependencies]
cfg_aliases = "0.2"

[dependencies]
owo-colors = "4.0"
log = "0.4"
thiserror = "1.0"
raw-window-handle = { version = "0.5", features = ["std"] }
arboard = "3.4.0"
# Servo
libservo = { git = "https://github.com/servo/servo.git", rev = "2a31e62", features = ["max_log_level", "native-bluetooth", "webdriver"] }
compositing_traits = { git = "https://github.com/servo/servo.git", rev = "2a31e62" }
webdriver_server = { git = "https://github.com/servo/servo.git", rev = "2a31e62" }
webrender = { git = "https://github.com/servo/webrender", branch = "0.64", features = ["capture"] }
sparkle = "0.1.26"
webxr = { git = "https://github.com/servo/webxr", features = ["headless"] }
env_logger = "0.10"
servo-media = { git = "https://github.com/servo/media" }
servo-media-dummy = { git = "https://github.com/servo/media" }
crossbeam-channel = "0.5"
getopts = "0.2.17"
surfman = { version = "0.9", features = ["chains", "sm-raw-window-handle"] }
winit = { version = "0.29", features = ["rwh_05"] }
cargo-packager-resource-resolver = { version = "0.1.1", features = [
  "auto-detect-format",
], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
libservo = { git = "https://github.com/servo/servo.git", rev = "2a31e62", features = [
  "no-wgl",
] }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
block = "0.1"
cocoa = "0.25"
core-graphics = "0.23"
objc = "0.2"
objc_id = "0.1"

[[test]]
name = "general"
harness = false
