workspace = {}

[package]
name = "verso"
version = "0.0.1"
authors = ["Wu Yu Wei"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "A web browser"
readme = "README.md"
repository = "https://github.com/european-browser/verso"
documentation = "https://docs.rs/verso"
categories = ["Web programming"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

[package.metadata.packager]
name = "verso"
product-name = "verso"
identifier = "com.eu-browser.verso"
version = "0.0.1"
before-each-package-command = "cargo build --release --features packager"
out-dir = "target/release"
resources = [
  "resources",
  "demo.html"
]
icons=[
  "resources/icons/icon256x256.png",
  "resources/icons/icon.ico"
]

[features]
default = []
# Exclusively for cargo packager command.
packager = ["dep:cargo-packager-resource-resolver"]

[build-dependencies]
cfg_aliases = "0.1"

[dependencies]
owo-colors = "4.0"
log = "0.4"
thiserror = "1.0"
raw-window-handle = { version = "0.5", features = ["std"] }
# Servo
libservo = { git = "https://github.com/servo/servo.git", rev = "245269c", features = ["max_log_level", "native-bluetooth", "webdriver"] }
crossbeam-channel = "0.5"
getopts = "0.2.17"
surfman = { version = "0.9", features = ["chains", "sm-angle", "sm-angle-default", "sm-x11", "sm-raw-window-handle"] }
winit = { version = "0.29", features = ["rwh_05"] }
# Cargo Packager
cargo-packager-resource-resolver = { version = "0.1", features = ["auto-detect-format"], optional = true }

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
block = "0.1"
cocoa = "0.25"
core-graphics = "0.23"
objc = "0.2"
objc_id = "0.1"


[[test]]
name = "general"
harness = false
