[workspace]
members = ["verso", "versoview_messages"]

[workspace.dependencies]
ipc-channel = "0.19"
serde = { version = "1.0", features = ["derive"] }
url = { version = "2.5.2", features = ["serde"] }

[package]
name = "versoview"
version = "0.0.1"
authors = ["Wu Yu Wei"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "An innovative web browser"
readme = "README.md"
homepage = "https://versotile.org/verso"
repository = "https://github.com/versotile-org/verso"
documentation = "https://docs.versotile.org/verso"
categories = ["web-programming"]

[package.metadata.packager]
name = "verso"
product-name = "verso"
identifier = "org.versotile.verso"
version = "0.0.1"
before-each-package-command = "python etc/package_libs.py"
resources = [
  "resources",
  "icons",
  "target/release/build/**/libEGL.dll",
  "target/release/build/**/libGLESv2.dll",
  "target/release/lib",
]
icons = ["icons/icon256x256.png", "icons/icon.ico"]

[package.metadata.packager.nsis]
appdata-paths = ["$LOCALAPPDATA/$IDENTIFIER"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

[features]
default = []
packager = ["dep:cargo-packager-resource-resolver"]
flatpak = []

[build-dependencies]
cfg_aliases = "0.2"

[dependencies]
arboard = "3.4.0"
crossbeam-channel = "0.5"
env_logger = "0.11"
euclid = "0.22"
getopts = "0.2.17"
gleam = "0.15"
glutin = "0.32.0"
glutin-winit = "0.5.0"
ipc-channel = { workspace = true }
keyboard-types = "0.7"
log = "0.4"
raw-window-handle = { version = "0.6", features = ["std"] }
sparkle = "0.1.26"
thiserror = "1.0"
winit = { version = "0.30", features = ["rwh_06"] }
# Servo repo crates
base = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
bluetooth = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
bluetooth_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
canvas = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
compositing_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
constellation = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
devtools = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
embedder_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
fonts = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
layout_thread_2020 = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
media = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
net = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
net_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
profile = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
profile_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
script = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
script_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
servo_config = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
servo_geometry = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
servo_url = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
webdriver_server = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
webrender_traits = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
webgpu = { git = "https://github.com/servo/servo.git", rev = "10aa485" }
# Servo org crates
servo-media = { git = "https://github.com/servo/media" }
servo-media-dummy = { git = "https://github.com/servo/media" }
style = { git = "https://github.com/servo/stylo", branch = "2024-10-04", features = ["servo"] }
style_traits = { git = "https://github.com/servo/stylo", branch = "2024-10-04", features = ["servo"] }
webrender = { git = "https://github.com/servo/webrender", branch = "0.65", features = ["capture"] }
webrender_api = { git = "https://github.com/servo/webrender", branch = "0.65" }
webxr = { git = "https://github.com/servo/webxr", features = ["headless"] }
webxr-api = { git = "https://github.com/servo/webxr" }
# Packager feature
cargo-packager-resource-resolver = { version = "0.1.1", features = [
  "auto-detect-format",
], optional = true }
url = { workspace = true }
headers = "0.3"
versoview_messages = { path = "./versoview_messages" }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc2 = "0.5"
objc2-app-kit = {version = "0.2", features = ["NSView", "NSResponder", "NSWindow"]}

[[test]]
name = "general"
harness = false

[profile.release-lto]
inherits = "release"
lto = true

# Tell clippy to allow e.g. #[cfg(macos)]
[lints.clippy]
mismatched_target_os = "allow"
