workspace = {}

[package]
name = "verso"
version = "0.0.1"
authors = ["Wu Yu Wei"]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "An innovative web browser"
readme = "README.md"
homepage = "https://versotile.org/verso"
repository = "https://github.com/versotile-org/verso"
documentation = "https://docs.versotile.org/verso"
categories = ["web-programming"]

[package.metadata.packager]
name = "verso"
product-name = "verso"
identifier = "org.versotile.verso"
version = "0.0.1"
before-each-package-command = "python etc/package_libs.py"
resources = [
  "resources",
  "icons",
  "target/release/build/**/libEGL.dll",
  "target/release/build/**/libGLESv2.dll",
  "target/release/lib",
]
icons = ["icons/icon256x256.png", "icons/icon.ico"]

[package.metadata.packager.nsis]
appdata-paths = ["$LOCALAPPDATA/$IDENTIFIER"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

[features]
default = []
packager = ["dep:cargo-packager-resource-resolver"]
flatpak = []

[build-dependencies]
cfg_aliases = "0.2"

[dependencies]
arboard = "3.4.0"
crossbeam-channel = "0.5"
env_logger = "0.10"
euclid = "0.22"
getopts = "0.2.17"
gleam = "0.15"
ipc-channel = "0.18"
keyboard-types = "0.7"
log = "0.4"
raw-window-handle = { version = "0.6", features = ["std"] }
sparkle = "0.1.26"
surfman = { version = "0.9", features = ["chains", "sm-raw-window-handle-06"] }
thiserror = "1.0"
winit = { version = "0.30", features = ["rwh_06"] }
# Servo repo crates
base = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
bluetooth = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
bluetooth_traits = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
canvas = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
compositing_traits = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
constellation = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
devtools = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
embedder_traits = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
fonts = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
layout_thread_2020 = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
media = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
net = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
profile = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
profile_traits = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
script = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
script_traits = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
servo_config = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
servo_geometry = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
servo_url = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
webdriver_server = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
webrender_traits = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
webgpu = { git = "https://github.com/servo/servo.git", rev = "28430ba" }
# Servo org crates
servo-media = { git = "https://github.com/servo/media" }
servo-media-dummy = { git = "https://github.com/servo/media" }
style = { git = "https://github.com/servo/stylo", branch = "2024-07-16", features = ["servo"] }
style_traits = { git = "https://github.com/servo/stylo", branch = "2024-07-16", features = ["servo"] }
webrender = { git = "https://github.com/servo/webrender", branch = "0.65", features = ["capture"] }
webrender_api = { git = "https://github.com/servo/webrender", branch = "0.65" }
webxr = { git = "https://github.com/servo/webxr", features = ["headless"] }
webxr-api = { git = "https://github.com/servo/webxr" }
# Packager feature
cargo-packager-resource-resolver = { version = "0.1.1", features = [
  "auto-detect-format",
], optional = true }
url = "2.5.2"

[target.'cfg(target_os = "windows")'.dependencies]
surfman = { version = "0.9", features = ["sm-angle-default"] }
mozangle = { version = "0.5.1", features = ["egl", "build_dlls"] }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc2 = "0.5"
objc2-app-kit = {version = "0.2", features = ["NSView", "NSResponder", "NSWindow"]}

[[test]]
name = "general"
harness = false
